apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "278"
  name: sterlingtoolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sterlingtoolkit
  template:
    metadata:
      labels:
        app: sterlingtoolkit
    spec:
      containers:
      - name: sterlingtoolkit
        image: quay.io/ibmtechgarage/sterlingtoolkit:1.0.8
        command: ["/bin/bash", "-ce", "cp /temp/*.jar /var/nfs-data/resources/ && tail -f /dev/null"]
        volumeMounts:
        - mountPath: /var/nfs-data/resources
          name: resources
        - mountPath: /var/nfs-data/documents
          name: documents
        - mountPath: /var/nfs-data/logs
          name: logs
      volumes:
      - name: documents
        persistentVolumeClaim:
          claimName: ibm-sfg-b2bi-sfg-documents
      - name: logs
        persistentVolumeClaim:
          claimName: ibm-sfg-b2bi-sfg-logs
      - name: resources
        persistentVolumeClaim:
          claimName: ibm-sfg-b2bi-sfg-resources