apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '220'
  name: qm-inst-svc
  namespace: tools
spec:
  license:
    accept: true
    license: L-APIG-BYHCL7
    metric: ProcessorValueUnit
    use: Development
  queueManager:
    metrics:
      enabled: true
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: '1'
        memory: 1Gi
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 100
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    route:
      enabled: true
    name: QM3
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    mqsc:
      - configMap:
          items:
            - static-definitions.mqsc
          name: mqcm
    logFormat: Basic
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    image: >-
      docker.io/ibmcom/mq
    storage:
      defaultClass: ibmc-file-gold-gid
      persistedData:
        enabled: true
      queueManager:
        class: ibmc-file-gold-gid
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false
  securityContext:
    initVolumeAsRoot: false
    # supplemantalGroups:
    #   - 99
    #   - 65534
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
            - name: MQ_QMGR_NAME
              value: qmgr
          name: qmgr
          securityContext:
            privileged: true
          resources: {}
  terminationGracePeriodSeconds: 30
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ''
  version: 9.2.3.0-r1
  web:
    enabled: true
