apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-sch-secret-gen
  annotations:
    argocd.argoproj.io/sync-wave: "205"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "create", "delete"]
