apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-sch-secret-gen
  annotations:
    argocd.argoproj.io/sync-wave: "204"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-sch-secret-gen
subjects:
- kind: ServiceAccount
  name: ibm-sch-secret-gen
  namespace: tools
