kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: itxa-nfs-claim
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: itxa-sc
  volumeMode: Filesystem