apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: itxa-nfs-claim
  annotations:
    argocd.argoproj.io/sync-wave: "240"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: itxa-sc
  volumeName: itxa-nfs-claim-common
  volumeMode: Filesystem