apiVersion: v1
kind: PersistentVolume
metadata:
  name: itxa-pv
  annotations:
    argocd.argoproj.io/sync-wave: "235"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 12Gi
  nfs:
    server: fsf-wdc0701n-fz.adn.networklayer.com
    path: /IBM02SEV2112072_156077/data01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: itxa-sc
